###################################################################
############ 1. FIT THE THREE MODELS ##############################
# Reads  data/wtp_data.csv
#        code/stan_models/{base_model,latent,latent_scale_model}.stan
# Writes data/posterior_base.RDS, data/posterior_latent.RDS,
#        data/posterior_latent_pred.RDS   (not in git; regenerated by this step)
#
# WTP_TEST=1 runs 20 warmup / 20 sampling iterations instead of 250 / 250.

library(rethinking)
library(cmdstanr)
library(posterior)
source("code/functions/utility.R")
source("code/prepare_data.R")

cat("fitting", SAMPLER_CHAINS, "chains x", SAMPLER_ITER, "iterations,",
  "N =", stan_data$N, "\n")

###################################################################
############ BASE MODEL (unrestricted MVN) ########################

base_model <- fit_model("code/stan_models/base_model.stan", stan_data, seed = 1)
saveRDS(extract.samples2(base_model), "data/posterior_base.RDS")

###################################################################
############ LATENT FACTOR MODEL ##################################

latent <- fit_model("code/stan_models/latent.stan", stan_data, seed = 2)
saveRDS(extract.samples2(latent), "data/posterior_latent.RDS")

###################################################################
############ PREDICTORS ON THE LATENT SCALE #######################

latent_pred <- fit_model(
  "code/stan_models/latent_scale_model.stan", stan_data,
  seed = 3
)
saveRDS(extract.samples2(latent_pred), "data/posterior_latent_pred.RDS")

cat("step 1 complete: three posteriors written to data/\n")
